version: "3.8"

services:
  migration:
    build: .
    volumes:
      - .:/django
    container_name: migration_database
    command: ./docker-cmd/start_database

  django:
    build: .
    volumes:
      - .:/django
      - static:/django/root/staticfiles
    expose:
      - 8000
    container_name: django
    depends_on:
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    command: ./docker-cmd/start_dev

  nginx_http:
    container_name: nginx_http
    image: nginx:latest
    depends_on:
      django:
        condition: service_started
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - static:/var/www/html/static/
      - ./nginx/dev/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    depends_on:
      migration:
        condition: service_completed_successfully

  celery_worker:
    build: .
    command: ./docker-cmd/start_celery_worker
    container_name: celery_worker
    volumes:
      - .:/django
    depends_on:
      redis:
        condition: service_healthy
      django:
        condition: service_started

  celery_beat:
    build: .
    command: ./docker-cmd/start_celery_beat
    container_name: celery_beat
    volumes:
      - .:/django
    depends_on:
      redis:
        condition: service_healthy
      django:
        condition: service_started

volumes:
  static:
